apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes-custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes-custom
  template:
  spec:
    hostNetwork: true
    metadata:
      labels:
        app: hello-kubernetes-custom
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.8
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
